version: '3.9'

services:
  client:
    container_name: react-ui
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./client:/app
